verbose: true
base_link: torso_lift_link
models:
 - name: arm
   type: chain
   frame: wrist_roll_link
 - name: camera
   type: camera3d
   frame: head_camera_rgb_optical_frame
   topic: /head_camera/depth_registered/points
 - name: cameradepth
   type: camera3d
   frame: head_camera_depth_optical_frame
 - name: camerargb
   type: camera2d
   frame: head_camera_rgb_optical_frame   
free_params:
 - shoulder_pan_joint
 - shoulder_lift_joint
 - upperarm_roll_joint
 - elbow_flex_joint
 - forearm_roll_joint
 - wrist_flex_joint
 - wrist_roll_joint
 - camera_fx
 - camera_fy
 - camera_cx
 - camera_cy
 - camera_z_offset
 - camera_z_scaling
 - cameradepth_fx
 - cameradepth_fy
 - cameradepth_cx
 - cameradepth_cy
 - cameradepth_z_offset
 - cameradepth_z_scaling
 - camerargb_fx
 - camerargb_fy
 - camerargb_cx
 - camerargb_cy
 - camerargb_z_offset
 - camerargb_z_scaling
free_frames:
 - name: head_camera_rgb_joint
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
 - name: head_camera_depth_joint
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
 - name: checkerboard
   x: true
   y: false
   z: true
   roll: false
   pitch: true
   yaw: false
error_blocks:
 - name: hand_eye
   type: camera3d_to_arm
   camera: camera
   arm: arm
 - name: restrict_camera
   type: outrageous
   param: head_camera_rgb_joint
   joint_scale: 0.0
   position_scale: 0.1
   rotation_scale: 0.1
 - name: gripper_depth
   type: camera3d_to_gripper
   camera: cameradepth
   gripper: arm
 - name: gripper_depth
   type: camera3d_to_led
   camera: camerargb
   gripper: arm

